#!/usr/bin/env bash
# Script that display from 1 to 2- with condition
c=1
while [ $c -le 20 ];
do
  echo $c
  case $c in 
  4)
    echo "bad luck from China"
    ;;
  9)
    echo "bad luck from Japan"
    ;;
  17)
    echo "bad luck from Italy"
    ;;
  esac
  (( c++ ))
done
